version: '3.8'

services:
  db:
    image: postgres
    container_name: django_db
    restart: always
    environment:
      POSTGRES_DB: db_stock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - django_assignment_network

  redis:
    image: redis
    container_name: django_redis
    restart: always
    ports:
      - "6379:6379"
    
    networks:
      - django_assignment_network

  web:
    build: .
    container_name: django_web
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

    networks:
      - django_assignment_network

  celery:
    build: .
    container_name: django_celery
    command: celery -A config worker -l info --pool=solo
    volumes:
      - .:/code
    depends_on:
      - redis
    
    networks:
      - django_assignment_network

  flower:
    build: .
    container_name: django_flower
    command: celery -A config flower
    ports:
      - "5555:5555"
    depends_on:
      - celery

    networks:
      - django_assignment_network

networks:
  django_assignment_network:
    driver: bridge
