# Generated by Django 5.1.1 on 2024-09-27 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f5fa7cf4-de1a-4b6c-8bbd-0d828efa1ebc'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('5fb7c2ed-a87b-4047-ac21-d54b5aeb8633'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
