# Generated by Django 5.1.1 on 2024-09-27 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_stockdata_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('233eefc2-f4d3-4790-8b9c-69bc91e9b5f7'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
