# Generated by Django 5.1.1 on 2024-09-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='volume',
            field=models.PositiveIntegerField(),
        ),
    ]
